
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author DEEPAK
 */
public class word extends javax.swing.JFrame {

    /**
     * Creates new form word
     */
    ImageIcon i;
    String []data={"KEYBOARD","MOUSE","COMPUTER","HELLO","DEEPAK","MAURYA","DEEPSHIKHA","ASHOK KUMAR MAURYA","KRISHNA MAURYA","RAHUL MAURYA","RASHMAI MAURYA","RUPAM MAURYA","BALL","APPLE","DADDY","ELEPHANT","FISH","GO","HAPPY","JUICE","MOTHER","OFF","TOILET"};
    String s;
    public word() {
        initComponents();
        setSize(1025,625);
        int select=tell();
        s=data[select];
        jLabel1.setText(s);
    }
    int tell()
    {
        int len=data.length;
        int result=(int)(len*(Math.random()));
        return result;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 30, 511, 104);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(jTextField1);
        jTextField1.setBounds(245, 299, 511, 83);

        jLabel2.setText(" ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(420, 130, 177, 136);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton1.setText("O K");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(159, 169, 126, 56);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jButton2.setText("NEXT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(687, 171, 125, 57);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox1.setMaximumRowCount(15);
        jPanel1.add(jComboBox1);
        jComboBox1.setBounds(410, 430, 189, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jComboBox1.setEnabled(true);
        String answer=jTextField1.getText();
        if(s.equals(answer))
        {
            i=new ImageIcon("correct.png");
            jLabel2.setIcon(i);
            jButton2.setEnabled(true);
            jComboBox1.removeAllItems();
            jComboBox1.addItem("RESULT");
            jComboBox1.addItem("NONE - all correct");
            
        }
        else
        {
            i=new ImageIcon("wrong.png");
            jButton2.setEnabled(false);
            jLabel2.setIcon(i);
            if(s.length()!=answer.length())
            {
                jComboBox1.removeAllItems();
                jComboBox1.addItem("MISTAKES");
                if(s.length()>answer.length())
                    jComboBox1.addItem("Input has LESS characters");
                else
                    jComboBox1.addItem("Input has MORE characters");
                jTextField1.setText("TEXT - "+s.length()+" INPUT - "+answer.length());
            }
            else
            {
                jComboBox1.removeAllItems();
                jComboBox1.addItem("MISTAKES");
                for(int j=0;j<s.length();++j)
                {
                    if(s.charAt(j)!=answer.charAt(j))
                    {
                        jComboBox1.addItem("Position "+(j+1));
                    }
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        jLabel2.setVisible(false);
        int select=tell();
        s=data[select];
        jLabel1.setText(s);
        jTextField1.requestFocus();
        jComboBox1.removeAllItems();
        jComboBox1.addItem("RESULT");
        jComboBox1.setEnabled(false);
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(word.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(word.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(word.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(word.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new word().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
